version: '3.8'

services:
  database:
    image: postgres:latest  # Utilisation de l'image officielle de PostgreSQL
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"  # Exposer le port 5432 de PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnetwork

volumes:
  pgdata:

networks:
  pgnetwork:
    driver: bridge